### ISSUE TITLE
Field validation errors

### ISSUE THREAD

**Issue by tobybessant** [Ebrisoft/Frontend#59]
When adding an issue as a landlord.

Conditions/Steps that caused bug:
1. Log in as landlord
2. Add issue
2. Set house to '26 Ebrington Street'
3. Low Priority
4. Add fields (fill out remaining fields)
5. Click 'Post'

Error should be thrown stating that all fields need to be filled in to submit - even though they are.

**Comment by Gubbsy** [comment]
Fixed
